/*
 *  CVS Version: $Id: linux-tunnel.c,v 1.2 2012/01/08 04:55:23 benny Exp $
 *
 *  Copyright (C) 2009-2015 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of CLICON.
 *
 *  CLICON is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  CLICON is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with CLICON; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 */
#ifdef HAVE_PYCLICON_CONFIG_H
#include "pyclicon_config.h" /* generated by config & autoconf */
#endif

#include <Python.h>

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <syslog.h>


/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>
#include <clicon/clicon_backend.h>

/* libpyclicon */
#include "libpyclicon.h"



typedef struct {
    PyObject *arg;
    PyObject *commit_func;
} dep_capsule;


/*
 * Commit callback. 
 */
static int
backend_commit(clicon_handle h,
	       char *db,
	       lv_op_t op,
	       char *key,
	       void *arg)
{
    long  retval = -1;
    PyObject *val = NULL;
    PyObject *handle = NULL;
    PyObject *backend = NULL;
    dep_capsule *cap = (dep_capsule *)arg;

    PyErr_Clear();
    if ((backend = PyImport_ImportModule("cliconbackend")) == NULL)
	goto quit;
    
    if ((handle = PyCapsule_New((void *)h, NULL, NULL)) == NULL)
	goto quit;
    
    
    if ((val = PyObject_CallMethod(backend, "_plugin_commit", "OOsisO",
		handle, cap->commit_func, db, op, key, cap->arg)) == NULL)
	goto quit;
    
    retval = IntAsLong(val);

quit:
    if (PyErr_Occurred())
	clicon_err(OE_PLUGIN, 0, "%s", ErrStringVerbose(0));

    Py_XDECREF(backend);
    Py_XDECREF(handle);
    Py_XDECREF(val);
    
    return retval;
}


typedef dbdep_handle_t (*dbdep_func_t)(clicon_handle, uint16_t, trans_cb, void *, char *);

static PyObject *
_backend_dbdep_func(PyObject *self, PyObject *args, dbdep_func_t func)
{
    int prio;
    char *key;
    clicon_handle h;
    PyObject *handle;
    PyObject *cb;
    PyObject *arg;
    dep_capsule *cap;

    if (!PyArg_ParseTuple(args, "OiOOs", &handle, &prio, &cb, &arg, &key))
        return NULL;

    if ((cap = malloc(sizeof(*cap))) == NULL) {
	clicon_err(OE_UNIX, errno, strerror(errno));
	return PyErr_NoMemory();
    }
    cap->arg = arg;
    Py_INCREF(arg);
    cap->commit_func = cb;
    Py_INCREF(cb);

    h = PyCapsule_GetPointer(handle, NULL);
    if (func(h, prio,  backend_commit, (void *)cap, key) == NULL) {
	free(cap);
	PyErr_SetString(PyExc_RuntimeError, "dbdep failed");
	return NULL;
    }

    Py_RETURN_NONE;
}

static PyObject *
_backend_dbdep(PyObject *self, PyObject *args)
{
    return _backend_dbdep_func(self, args, dbdep);
}

static PyObject *
_backend_dbdep_tree(PyObject *self, PyObject *args)
{
    return _backend_dbdep_func(self, args, dbdep_tree);
}

static PyObject *
_backend_dbdep_validate(PyObject *self, PyObject *args)
{
    return _backend_dbdep_func(self, args, dbdep_validate);
}

static PyObject *
_backend_dbdep_tree_validate(PyObject *self, PyObject *args)
{
    return _backend_dbdep_func(self, args, dbdep_tree_validate);
}



static PyMethodDef backend_module_methods[] = {
    {"_dbdep", (PyCFunction)_backend_dbdep, METH_VARARGS,
     "Register database dependency"
    },
    {"_dbdep_tree", (PyCFunction)_backend_dbdep_tree, METH_VARARGS,
     "Register database dependency"
    },
    {"_dbdep_validate", (PyCFunction)_backend_dbdep_validate, METH_VARARGS,
     "Register database dependency"
    },
    {"_dbdep_tree_validate", (PyCFunction)_backend_dbdep_tree_validate, METH_VARARGS,
     "Register database dependency"
    },

    {NULL, NULL, 0, NULL}
};

MOD_INIT(_backend)
{
    PyObject* m;

    MOD_DEF(m,"_cliconbackend","Python CLICON backend", backend_module_methods);
    if (m == NULL)
        return MOD_ERROR_VAL;
    
    PyModule_AddIntConstant(m, (char *) "TRANS_CB_COMMIT", TRANS_CB_COMMIT);
    PyModule_AddIntConstant(m, (char *) "TRANS_CB_VALIDATE", TRANS_CB_VALIDATE);
    PyModule_AddIntConstant(m, (char *) "TRANS_CB_BOTH", TRANS_CB_BOTH);

    PyModule_AddIntConstant(m, (char *) "LV_DELETE", LV_DELETE);
    PyModule_AddIntConstant(m, (char *) "LV_SET", LV_SET);
    PyModule_AddIntConstant(m, (char *) "LV_MERGE", LV_MERGE);

    return MOD_SUCCESS_VAL(m);
}


/*
 * plugin call
 */
static int
plugin_call(clicon_handle h, char *func)
{
    int retval = -1;
    PyObject *handle = NULL;
    PyObject *backend = NULL;
    PyObject *val = NULL;
    
    if (Py_IsInitialized() == 0)
	return 0;

    PyErr_Clear();
    if ((backend = PyImport_ImportModule("cliconbackend")) == NULL)
	goto quit;
    
    if ((handle = PyCapsule_New((void *)h, NULL, NULL)) == NULL)
	goto quit;
    
    val = PyObject_CallMethod(backend, func, "O", handle);
    if (val == NULL)
	goto quit;
    
    retval = PyLong_AsLong(val);

quit:
    if (PyErr_Occurred())
	clicon_err(OE_PLUGIN, 0, "%s", ErrStringVerbose(0));
    Py_XDECREF(backend);
    Py_XDECREF(handle);
    Py_XDECREF(val);

    return retval;
}

/*
 * Plugin initialization
 */
int
plugin_init(clicon_handle h)

{
    char *dir;
    int retval = -1;

    PyImport_AppendInittab("_cliconbackend", MOD_INITFUNC(_backend));
    Py_InitializeEx(0);

    /* Append application plugin directory */
    if ((dir = clicon_option_str(h, "CLICON_BACKEND_DIR")) == NULL) {
	clicon_err(OE_PLUGIN, 0, "CLICON_BACKEND_DIR not set");
	goto quit;
    }
    if (syspath_insert(dir) < 0)
	goto quit;

    /* Append CLICON python module directory */
    if (syspath_insert(PYCLICON_MODDIR) < 0)
	goto quit;
    
    retval = plugin_call(h, "_plugin_init");

    
 quit:
    if (retval <= 0)  /* Error or no loaded plugins */
	Py_Finalize();

    if (debug && retval == 0)
	clicon_debug(1, "DEBUG: No python plugins loaded");
    else if (retval > 0)
	clicon_debug(1, "DEBUG: Loaded %d python plugins", retval);

    return (retval < 0) ? -1 : 0;
}


/*
 * plugin start
 */
int
plugin_start(clicon_handle h, int argc, char **argv)
{
    int i;
    int retval = -1;
    PyObject *item;
    PyObject *handle = NULL;
    PyObject *backend = NULL;
    PyObject *val = NULL;
    PyObject *Argv = NULL;
    
    if (Py_IsInitialized() == 0)
	return 0;

    PyErr_Clear();
    if ((backend = PyImport_ImportModule("cliconbackend")) == NULL)
	goto quit;
    
    if ((handle = PyCapsule_New((void *)h, NULL, NULL)) == NULL)
	goto quit;
    if ((Argv = PyTuple_New(argc)) == NULL)
	goto quit;

    for (i = 0; i < argc; i++) {
	if ((item = StringFromString(argv[i])) == NULL)
	    goto quit;
	PyTuple_SET_ITEM(Argv, i, item); /* name ref transferred */
    }
    
    val = PyObject_CallMethod(backend,"_plugin_start","OiO", handle, argc, Argv);
    if (val == NULL)
	goto quit;
    
    retval = PyLong_AsLong(val);

quit:
    if (PyErr_Occurred())
	clicon_err(OE_PLUGIN, 0, "%s", ErrStringVerbose(0));
    Py_XDECREF(backend);
    Py_XDECREF(handle);
    Py_XDECREF(Argv);
    Py_XDECREF(val);

    return retval;
}


/*
 * plugin reset
 */
int
plugin_reset(clicon_handle h, char *dbname)
{
    return plugin_call(h, "_plugin_reset");
}


int
plugin_exit(clicon_handle h)
{ 
    int retval;

    retval = plugin_call(h, "_plugin_exit");
    Py_Finalize();

    return retval;
}



/*
 * transaction begin
 */
int
transaction_begin(clicon_handle h)
{
    return plugin_call(h, "_transaction_begin");
}

/*
 * transaction complete
 */
int
transaction_complete(clicon_handle h)
{
    return plugin_call(h, "_transaction_complete");
}


/*
 * transaction end
 */
int
transaction_end(clicon_handle h)
{
    return plugin_call(h, "_transaction_end");
}



/*
 * transaction abort
 */
int
transaction_abort(clicon_handle h)
{
    return plugin_call(h, "_transaction_abort");
}


/*
 * Generate readable error if someone tries to import me
 */
MOD_INIT(_cligen)
{
    PyErr_Format(PyExc_RuntimeError, "%s is not a Python module but a CLICON plugin", __FILE__);
    return MOD_ERROR_VAL;
}
