/*
 *  CVS Version: $Id: linux-tunnel.c,v 1.2 2012/01/08 04:55:23 benny Exp $
 *
 *  Copyright (C) 2009-2015 Olof Hagsand and Benny Holmgren
 *
 *  This file is part of CLICON.
 *
 *  CLICON is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  CLICON is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with CLICON; see the file COPYING.  If not, see
 *  <http://www.gnu.org/licenses/>.
 */
#ifdef HAVE_PYCLICON_CONFIG_H
#include "pyclicon_config.h" /* generated by config & autoconf */
#endif

#include <Python.h>

/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>
#include <clicon/clicon_cli.h>

/* libpyclicon */
#include "libpyclicon.h"

static PyObject *
_cli_syntax_mode(PyObject *args)
{
    char *mode;
    clicon_handle h;
    PyObject *handle;
    
    if (!PyArg_ParseTuple(args, "O", &handle))
        return NULL;
    h = PyCapsule_GetPointer(handle, NULL);
  
    if ((mode = cli_syntax_mode(h)) == NULL)
        Py_RETURN_NONE;

    return StringFromString(mode);
}

static PyObject *
_cli_set_syntax_mode(PyObject *args)
{
    char *mode;
    clicon_handle h;
    PyObject *handle;
    
    if (!PyArg_ParseTuple(args, "Os", &handle, &mode))
        return NULL;
    h = PyCapsule_GetPointer(handle, NULL);
  
    if (cli_set_syntax_mode(h, mode) == 0)
        Py_RETURN_FALSE;
    Py_RETURN_TRUE;
}

static PyObject *
_cli_set_prompt(PyObject *args)
{
    char *mode;
    char *prompt;
    clicon_handle h;
    PyObject *handle;
    
    if (!PyArg_ParseTuple(args, "Oss", &handle, &mode, &prompt))
        return NULL;
    h = PyCapsule_GetPointer(handle, NULL);
  
    if (cli_set_prompt(h, mode, prompt) == 0)
        Py_RETURN_FALSE;
    Py_RETURN_TRUE;
}

static PyObject *
_cli_comment(PyObject *args)
{
    clicon_handle h;
    PyObject *handle;
    char comment[2] = {'\0','\0'};

    if (!PyArg_ParseTuple(args, "O", &handle))
        return NULL;
    h = PyCapsule_GetPointer(handle, NULL);
  
    comment[0] = cli_comment(h);
    return StringFromString(comment);
}

static PyObject *
_cli_set_comment(PyObject *args)
{
    clicon_handle h;
    PyObject *handle;
    char *comment;
    
    if (!PyArg_ParseTuple(args, "Os", &handle, &comment))
        return NULL;
    h = PyCapsule_GetPointer(handle, NULL);
  
    cli_set_comment(h, comment[0]);
    return _cli_comment(args);
}

static PyObject *
_cli_set(PyObject *args)
{
    PyObject *handle;
    PyObject *vars;
    PyObject *arg;
    PyObject *Cv;
    PyObject *Vr;
    cg_var *cv;
    cvec *vr = NULL;
    int retval = -1;
    clicon_handle h;

    if (!PyArg_ParseTuple(args, "OOO", &handle, &vars, &arg))
        return NULL;
    
    h = PyCapsule_GetPointer(handle, NULL);

    if ((Vr = PyObject_CallMethod(vars, "__cvec_from_Cvec", NULL)) == NULL)
      return NULL;
    vr = PyCapsule_GetPointer(Vr, NULL);
    Py_XDECREF(Vr);

    if ((Cv = PyObject_CallMethod(arg, "__cv", NULL)) == NULL)
      return NULL;
    cv = PyCapsule_GetPointer(Cv, NULL);
    Py_XDECREF(Cv);

    retval = cli_set(h, vr, cv);
    cvec_free(vr);

    return PyLong_FromLong(retval);
}


static PyMethodDef cli_module_methods[] = {
    {"_cli_syntax_mode", (PyCFunction)_cli_syntax_mode, METH_VARARGS,
     "Get CLI syntax mode"
    },
    {"_cli_set_syntax_mode", (PyCFunction)_cli_set_syntax_mode, METH_VARARGS,
     "Set CLI syntax mode"
    },
    {"_cli_set_prompt", (PyCFunction)_cli_set_prompt, METH_VARARGS,
     "Set CLI prompt"
    },
    {"_cli_comment", (PyCFunction)_cli_comment, METH_VARARGS,
     "Get CLI comment character"
    },
    {"_cli_set_comment", (PyCFunction)_cli_set_comment, METH_VARARGS,
     "Set CLI comment character"
    },
    {"_cli_set", (PyCFunction)_cli_set, METH_VARARGS,
     "Set database values"
    },

    {NULL, NULL, 0, NULL}
};



MOD_INIT(_cli)
{
    PyObject* m;

    MOD_DEF(m,"_cliconcli","Python CLICON CLI frontend", cli_module_methods);
    if (m == NULL)
        return MOD_ERROR_VAL;
    
    PyModule_AddIntConstant(m, (char *) "CLI_PROMPT_LEN",  CLI_PROMPT_LEN);
    PyModule_AddStringConstant(m, (char *) "CLI_DEFAULT_PROMPT",
			       CLI_DEFAULT_PROMPT);

    PyModule_AddIntConstant(m, (char *) "CANDIDATE_DB_NONE", 
			    CANDIDATE_DB_NONE);
    PyModule_AddIntConstant(m, (char *) "CANDIDATE_DB_PRIVATE",
			    CANDIDATE_DB_PRIVATE);
    PyModule_AddIntConstant(m, (char *) "CANDIDATE_DB_SHARED",
			    CANDIDATE_DB_SHARED);
    PyModule_AddIntConstant(m, (char *) "CANDIDATE_DB_CURRENT", 
			    CANDIDATE_DB_CURRENT);


    return MOD_SUCCESS_VAL(m);
}

/*
 * plugin call
 */
static int
plugin_call(clicon_handle h, char *func)
{
    int retval = -1;
    PyObject *handle = NULL;
    PyObject *cli = NULL;
    PyObject *val = NULL;
    
    if (Py_IsInitialized() == 0)
	return 0;

    PyErr_Clear();
    if ((cli = PyImport_ImportModule("cliconcli")) == NULL)
	goto quit;
    
    if ((handle = PyCapsule_New((void *)h, NULL, NULL)) == NULL)
	goto quit;
    
    val = PyObject_CallMethod(cli, func, "O", handle);
    if (val == NULL)
	goto quit;
    
    retval = PyLong_AsLong(val);

quit:
    if (PyErr_Occurred())
	clicon_err(OE_PLUGIN, 0, "%s", ErrStringVerbose(0));
    Py_XDECREF(cli);
    Py_XDECREF(handle);
    Py_XDECREF(val);

    return retval;
}



/*
 * Plugin initialization
 */
int
plugin_init(clicon_handle h)

{
    char *dir;
    int retval = -1;

    PyImport_AppendInittab("_cliconcli", MOD_INITFUNC(_cli));
    Py_InitializeEx(0);

    /* Append application plugin directory */
    if ((dir = clicon_option_str(h, "CLICON_CLI_DIR")) == NULL) {
	clicon_err(OE_PLUGIN, 0, "CLICON_CLI_DIR not set");
	goto quit;
    }
    if (syspath_insert(dir) < 0)
	goto quit;

    /* Append CLICON python module directory */
    if (syspath_insert(PYCLICON_MODDIR) < 0)
	goto quit;
    
    retval = plugin_call(h, "_plugin_init");

    
 quit:
    if (retval <= 0)  /* Error or no loaded plugins */
	Py_Finalize();

    if (debug && retval == 0)
	clicon_debug(1, "DEBUG: No python plugins loaded");
    else if (retval > 0)
	clicon_debug(1, "DEBUG: Loaded %d python plugins", retval);

    return (retval < 0) ? -1 : 0;
}

