/*
 *  CVS Version: $Id: clicon_xml.c,v 1.25 2013/09/18 19:16:27 olof Exp $
 *
  Copyright (C) 2009-2014 Olof Hagsand and Benny Holmgren

  This file is part of CLICON.

  CLICON is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 3 of the License, or
  (at your option) any later version.

  CLICON is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with CLICON; see the file COPYING.  If not, see
  <http://www.gnu.org/licenses/>.

 *
 * XML code
 */
#ifdef HAVE_CONFIG_H
#include "clicon_config.h" /* generated by config & autoconf */
#endif

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <ctype.h>
#include <string.h>
#include <arpa/inet.h>
#include <assert.h>
#include <syslog.h>
#include <fcntl.h>
#include <netinet/in.h>

/* cligen */
#include <cligen/cligen.h>

/* clicon */

#include "clicon_string.h"
#include "clicon_queue.h"
#include "clicon_hash.h"
#include "clicon_db.h"
#include "clicon_chunk.h"
#include "clicon_handle.h"
#include "clicon_spec.h"
#ifdef USE_DBSPEC_PT
#include "clicon_dbspec_parsetree.h"
#endif /* USE_DBSPEC_PT */
#include "clicon_yang.h"
#include "clicon_options.h"
#include "clicon_lvalue.h"
#include "clicon_dbutil.h"
#include "clicon_lvmap.h"
#include "clicon_buf.h"
#include "xmlgen_xml.h"
#include "xmlgen_xsl.h"
#include "clicon_log.h"
#include "clicon_err.h"
#include "clicon_xml.h"

/*
 * var2xml_all
 * create sub-elements for every variable in vh
 * EXCEPT in the uvh list which are the 'unique' variables of vectors
 * that shpould already have been added.
 */
static int
var2xml_all(struct xml_node *xnp, cvec *vr, cvec *skipvr)
{
    struct xml_node *xn;
    struct xml_node *xnb;
    cg_var          *cv = NULL;
    char            *vnam;
    char            *str;

    /* Print/Calculate varible format string if variable exist */
    cv = NULL;
    while ((cv = cvec_each(vr, cv))) {
	vnam = cv_name_get(cv);
	if (cvec_find(skipvr, vnam))
	    continue; /* skipe the ones in skiplist */
	/* create a parse-node here */
	if ((xn = xml_new(vnam, xnp)) == NULL)
	    goto catch;
	if ((str = cv2str_dup(cv)) == NULL)
	    goto catch;
	if ((xnb = xml_new("body", xn)) == NULL) {
	    free(str);
	    goto catch;
	}
	xnb->xn_type = XML_BODY;
	xnb->xn_value = str;
    } /* if var_find */
  catch:
    return 0;
}


/*
 * XXX: Is this really necessary?
 */
static int
db2xml_sort (const void *p1, const void *p2)
{
    char *ptr1, *ptr2;
    char *s1 = ((struct db_pair *)p1)->dp_key;
    char *s2 = ((struct db_pair *)p2)->dp_key;
    
    ptr1 = s1 + strlen(s1)-1;
    while (ptr1 > s1 && isdigit(*ptr1))
      ptr1--;
    if (*ptr1 != '.')
	goto regex;
    ptr1++;

    ptr2 = s2 + strlen(s2)-1;
    while (ptr2 > s2 && isdigit(*ptr2))
      ptr2--;
    if (*ptr2 != '.')
	goto regex;
    ptr2++;

    if(ptr1-s1 == ptr2-s2 && strncmp(s1, s2, ptr1-s1) == 0)
	return lvmap_get_dbvector_sort(p1, p2);
    
regex:
    return lvmap_get_dbregex_sort (p1, p2);
}


/* 
   Optimization of xml_xpath(xn, "/node[key=str]")

   xn
   | \ 0..N, where N can be very large
   node "CreateSender..."
   |
   key "SenderName"
   |
   body value== str
*/

static struct xml_node *
xml_xfind(struct xml_node *xn, char *node, char *key, char *str)
{
    struct xml_node *xnode;
    struct xml_node *xkey;
    struct xml_node *xbody;

    xnode = NULL;
    while ((xnode = xml_child_each(xn, xnode, XML_ELEMENT)) != NULL) {
	if (strcmp(node, xnode->xn_name))
	    continue;
	xkey = NULL;
	while ((xkey = xml_child_each(xnode, xkey, XML_ELEMENT)) != NULL) {
	    if (strcmp(key, xkey->xn_name))
		continue;
	    xbody = NULL;
	    while ((xbody = xml_child_each(xkey, xbody, XML_BODY)) != NULL) {
		if (strcmp(str, xbody->xn_value))
		    continue;
		goto done;
	    }
	    break; /* Assume only one matching key */
	}
    }
    xnode = NULL; /* not found */
  done:
    return xnode;
}

/*
 * dbkey2xml
 * key is a name of a unique variable, we look it up in variable list vh
 * and then find the object it corresponds to in xml tree xn.
 * XXX: A[] $!a; A[].B[] $!a $!b should be shown as:
 <Group>
  <GroupName>G</GroupName>
  <Node>
    <NodeName>N</NodeName>
    <Port>4242</Port>
  </Node>
</Group>

Now it is shown with this appended:

<Group>
  <GroupName>G</GroupName>
</Group>

 */
int
dbkey2xml(struct db_spec *db_spec, 
	  struct xml_node *xnt, 
	  char *key, 
	  char *val, 
	  int vlen)
{
    struct xml_node *xnp;   /* parent */
    struct xml_node *xn = NULL;
    struct xml_node *xb;
    struct xml_node *xv;
    char            *subkey;
    struct db_spec *subspec;
    cvec           *vr;
    cvec           *subvr;
    cg_var         *v;
    cg_var         *ncv;
    char           **vec;
    int              nvec;
    int              isvec;
    int              n;
    char            *str;
    char            *bstr;
    char            *fmt;
    cvec            *uvr = NULL; /* unique var set */
    int              prevspec;

    if (debug > 1)
	fprintf(stderr, "%s: key:%s\n", __FUNCTION__, key);
    xnp = xnt;
    if (key_isvector_n(key) || key_iskeycontent(key))
	return 0;
    if ((vec = clicon_strsplit(key, ".", &nvec, __FUNCTION__)) == NULL)
	goto catch;
    if ((vr = lvec2cvec(val, vlen)) == NULL)
	goto catch;
    uvr = cvec_new(0);
    prevspec = 1;
    /* 
     * semantics of prevspec:
     * It is 1 initially.
     * If No spec is found (eg A when A[]) it set to 0.
     * else if it is a vector it is set, or if it is not set previosly.
     * If prevspec is not set and a spec is not found, then an xml-node is 
     * 
     */
    for (n=0; n<nvec; n++){
	if ((subkey = clicon_strjoin(n+1, vec, ".", __FUNCTION__)) == NULL)
	    goto catch;
	/* a vector subkey may not have a spec: spec: a.b[], then a.b has
	   no spec */
	if ((subspec = key2spec_key(db_spec, subkey)) == NULL){
	    if (!prevspec){
		if  ((xn = xml_find(xnp, vec[n-1])) == NULL)
		    if ((xn = xml_new(vec[n-1], xnp)) == NULL)
			goto catch;
		xnp = xn;
	    }
	    prevspec = 0;
	    continue;
	}
	if (debug>1)
	    fprintf(stderr, "%s: subkey:%s\n", __FUNCTION__, subkey);
	isvec = key_isvector(subspec->ds_key);
	if (debug>1)
	    fprintf(stderr, "%s: isvec:%d\n", 
		    __FUNCTION__, isvec);
	if (isvec){ /* subkey is vector, on the form a.b.<n> */
	    prevspec++;
	    /* find unique variable from spec (assume only one) */
	    subvr = db_spec2cvec(subspec);
	    v = NULL; 		
	    while ((v = cvec_each(subvr, v)))
		if (cv_flag(v, V_UNIQUE) && !cvec_find(uvr, cv_name_get(v)))
		    break;
	    if (v == NULL) /* bad spec */
		continue;
	    if ((ncv = cvec_add(uvr, CGV_INT)) == NULL)
		goto catch;
	    if (cv_name_set(ncv, cv_name_get(v)) == NULL)
		goto catch;
	    cv_flag_set(ncv, V_UNSET);
	    if (debug>1)
		fprintf(stderr, "%s: unique var:%s\n", 
			__FUNCTION__, cv_name_get(v));
	    /* get key's value of v */
	    if ((v = cvec_find(vr, cv_name_get(v))) == NULL)
		continue; /* bad spec */
	    if ((str = cv2str_dup(v)) == NULL)
		continue; /* bad spec */
	    if (debug>1)
		fprintf(stderr, "%s: var value:%s\n", 
			__FUNCTION__, str);
	    if ((fmt = chunk_sprintf(__FUNCTION__, "/%s[%s=%s]",
				     vec[n-1], cv_name_get(v), str)) == NULL) {
		free(str);
		goto catch;
	    }
	    if (debug>1)
		fprintf(stderr, "%s: fmt:%s\n", __FUNCTION__, fmt);
	    /* example: /Foo[SenderName=S998] */

#if 0 /* we are trying to optimize */
	    if  ((xn = xml_xpath(xnp, fmt)) != NULL){
#else
	    if (1) /* XXX: Is this necessary? */
	    if  ((xn = xml_xfind(xnp, vec[n-1], cv_name_get(v), str)) != NULL){
#endif
		if ((bstr = xml_get_body2(xn, cv_name_get(v))) == NULL){
		    free(str);
		    continue; /* shouldnt happen */
		}
		if (strcmp(str, bstr)==0){ /* does exist */
		    free(str);
		    xnp = xn;
		    continue;
		}
	    }
	    assert(n>0);
	    if (debug>1)
		fprintf(stderr, "%s: create <%s><%s>%s\n", 
			__FUNCTION__, vec[n-1], cv_name_get(v), str);
	    if ((xn = xml_new(vec[n-1], xnp)) == NULL){
		free(str);
		goto catch;
	    }
	    if ((xv = xml_new(cv_name_get(v), xn)) == NULL){
		free(str);
		goto catch;
	    }
	    xv->xn_index++;
	    if ((xb = xml_new("body", xv)) == NULL){
		free(str);
		goto catch;
	    }
	    xb->xn_type = XML_BODY;
	    xb->xn_value = str;
	} /* vector */
	else{
	    if (!prevspec){
		prevspec++;
		if  ((xn = xml_find(xnp, vec[n-1])) == NULL)
		    if ((xn = xml_new(vec[n-1], xnp)) == NULL)
			goto catch;
		xnp = xn;
	    }
	    if  ((xn = xml_find(xnp, vec[n])) == NULL){
		if (debug>1)
		    fprintf(stderr, "%s: create <%s> parent:%s\n", 
			    __FUNCTION__, vec[n], xnp->xn_name);
		if ((xn = xml_new(vec[n], xnp)) == NULL)
		    goto catch;
	    }
	}
	xnp = xn;
    } /* for */
    if (var2xml_all(xn, vr, uvr) < 0)
	goto catch;
    if (uvr) /* clear unique var set */
	cvec_free(uvr);
    cvec_free (vr);
    vr = NULL;
    unchunk_group(__FUNCTION__);  
    return 0;
  catch:
    unchunk_group(__FUNCTION__);  
    return -1;
}

/*
 * dbpairs2xml
 * Given a list of key/val pairs, return a xml parse-tree.
 * Sort them.
 * Build a parse-tree in xml, and return that.
 */
static int
dbpairs2xml(struct db_pair *pairs, 
	    int npairs, 
	    struct db_spec *db_spec, 
	    struct xml_node *xnt)
{
    int              i;
    int retval = -1;

    /* XXX: Why do we need to sort the pairs ? */
    if(0)    qsort (pairs, npairs, sizeof (struct db_pair), db2xml_sort);
    for (i=0; i<npairs; i++) {
	if (dbkey2xml(db_spec, 
		      xnt, 
		      pairs[i].dp_key, 
		      pairs[i].dp_val, 
		      pairs[i].dp_vlen) < 0)
	    goto catch;
    } /* for pairs */
    retval = 0;
  catch:
    unchunk_group(__FUNCTION__);  
    return retval;
} /* dbpairs2xml */

/*
 * db2xml
 * Given a database go through all keys and return an xml parse-tree.
 * First get all keys from db by general match, getting db_pairs (we only use the key)
 * Sort them.
 * Build a parse-tree in xml, and return that.
 * dont work:
 * system.hostname (only hostname)
 * inet.address (only hostname)
 * XXX: uvh?
 */
struct xml_node *
db2xml(char *dbname, struct db_spec *db_spec, char *toptag)
{
    struct db_pair   *pairs;
    int               npairs;
    struct xml_node  *xt;

    if ((xt = xml_new(toptag, NULL)) == NULL)
	goto catch;
    if ((npairs = db_regexp(dbname, "^.*$", __FUNCTION__, &pairs, 0)) < 0)
	goto catch;
    if (dbpairs2xml(pairs, npairs, db_spec, xt) < 0)
	goto catch;
    unchunk_group(__FUNCTION__);  
    return xt;
  catch:
    if (xt)
	xml_free(xt);
    unchunk_group(__FUNCTION__);  
    return NULL;
}

/*
 * key2xml
 * Given a database and a key in that database,
 * Return an xml parsetree.
 */
int
key2xml(char *key, char *dbname, struct db_spec *db_spec, struct xml_node *xtop)
{
    char             *lvec = NULL;
    size_t            lvlen;
    int               retval = -1;

    if (db_get_alloc(dbname, key, (void*)&lvec, &lvlen) < 0)
	goto catch;
    if (dbkey2xml(db_spec, xtop, key, lvec, lvlen) < 0)
	goto catch;
    retval = 0;
  catch:
    if (lvec)
	free(lvec);
    return retval;
}



/*
 * A node is a leaf if it contains a body.
 */
static struct xml_node *
leaf(struct xml_node *xn)
{
    struct xml_node *xc = NULL;

    while ((xc = xml_child_each(xn, xc, XML_BODY)) != NULL)
	break;
    return xc;
}

/*
 * xml2db_tranform_key
 * Input args:
 *   xn       xml-parse tree of a 'superleaf', ie parent to leafs
 *   dbspex   Database specification 
 *   dbname   Name of a database we are creating
 *   key      A database key, example ipv4.domain
 *   spec     A database spec entry.
 *   uv       Unique (key) variable vector
 */
static int
xml2db_transform_key(struct xml_node *xn, 
		     struct db_spec  *dbspec, 
		     char            *dbname, 
		     int              isvector,
		     char           **key, 
		     struct db_spec  *spec,
		     cvec            *uv)
{
    struct xml_node  *xc;          /* xml parse-tree child (leaf) */
    struct xml_node  *xb;          /* xml body (text) */
    cvec             *vhds;          /* spec variable list */
    cg_var           *v;           /* single variable */
//    cg_var           *v1;           /* single variable */
    int               retval = -1; 
    cvec             *vh1 = NULL;
    cg_var           *cv;
    int               index;
    int               len;
    char             *k;
    int               matched = 0;

    /* vh1 is list of variables, first unique, then rest */
    if ((vh1 = cvec_new(0)) == NULL) 
	goto catch;
    /* 
     * First add unique variables
     */
    v = NULL;
    while ((v = cvec_each(uv, v))){
	if((cv = cvec_add_cv(vh1, v)) == NULL) {
	    clicon_err(OE_UNIX, errno, "cvec_add_cv");
	    goto catch;
	}
    }
    /* 
     * Then add variables found in XML and check with dbspec
     */
    vhds = db_spec2cvec(spec);
    xc = NULL;
    while ((xc = xml_child_each(xn, xc, XML_ELEMENT)) != NULL){
	xb = NULL;
	while ((xb = xml_child_each(xc, xb, XML_BODY)) != NULL){
	    /* unique cv already added? */
	    if (spec->ds_vector || (cv = cvec_find(vh1, xc->xn_name)) == NULL){ 
		if ((v = cvec_find(vhds, xc->xn_name)) == NULL)
		    continue;
		if ((cv = cvec_add_cv(vh1, v)) == NULL){
		    clicon_err(OE_UNIX, errno, "cvec_add");
		    goto catch;
		}
	    }
	    cv_parse(xb->xn_value, cv);
	    break; /* one body */
	} /* for body */
    }
    if (isvector){
	if ((index = db_lv_vec_find(dbspec, dbname, *key, vh1, &matched)) < 0)
	    goto catch;
	assert(index>=0);
	k = strdup(*key);
	len  = strlen(k)+1+index/10+1+1; /* .n */
	free(*key);
	if ((*key = malloc(len+3)) == NULL) /* bit-stuff to 32-bit */
	    goto catch;
	snprintf(*key, len, "%s.%u", k, index);
	free(k);
	if (db_lv_set(spec, dbname, *key, vh1, LV_SET) < 0)
	    goto catch;
#if 0 /* db_lv_vec_set() is inlined above for optimization reasons. XXX: Maybe can
       reinstall when optinmization finalized? */
	if (db_lv_vec_set(dbspec, dbname, k, vh1, LV_SET, &index) < 0)
	    goto catch;
#endif
    }
    else 
	if (db_lv_set(spec, dbname, *key, vh1, LV_SET) < 0)
	    goto catch;
    retval = 0;
  catch:
    if (vh1)
	cvec_free(vh1);
    unchunk_group(__FUNCTION__);
    return retval;
}

/*
 * key2spec
 * given key and key-prefix, return spec if exact found.
 * if not, there may be a partial match, ie continue parsing.
 * key is malloced, needs free after use
 */
static int
key2spec(char *name, 
	 char *key0, 
	 struct db_spec *db_spec, 
	 struct db_spec **specp, 
	 int *partial,
	 char **key)
{
    char            *vkey; /* vector key */
    struct db_spec  *ds;
    int              retval = -1;
    int              len;

    *partial = 0;
    len = strlen(name);
    if (key0){
	len += strlen(key0) + 1;
	if ((*key = malloc(len+1)) == NULL){
	    clicon_err(OE_UNIX, errno, "malloc");
	    goto done;
	}
	snprintf(*key, len+1, "%s.%s", key0, name);
    }
    else{
	*key = strdup(name);
    }
    if ((vkey = chunk_sprintf(__FUNCTION__, "%s[]", *key)) == NULL)
	goto done;

    /* Try match key or key[] with spec */ 
    for (ds=db_spec; ds; ds=ds->ds_next){
	if (strcmp(*key, ds->ds_key) == 0)
	    break;
	if (strcmp(vkey, ds->ds_key) == 0){
	    free(*key);
	    if ((*key = strdup(vkey)) == NULL){
		clicon_err(OE_UNIX, errno, "strdup");
		goto done;
	    }
	    break;
	}
	if (strncmp(*key, ds->ds_key, len) == 0)
	    (*partial)++;
    }
    if (ds != NULL)
	*specp = ds;
    retval = 0;
  done:
    unchunk_group(__FUNCTION__);
    return retval;
}

/*
 * xml2db_1
 */
static int
xml2db_1(struct xml_node *xn, 
	 struct db_spec *dbspec, 
	 char *dbname, 
	 cvec *uv,
	 char *basekey0,     /* on format A[].B[] */
	 char *key0
    )         /* on format A.2.B.3 */
{
    int               retval = -1;
    int               superleaf;
    struct xml_node  *xc;
    char             *basekey = NULL;
    char             *key = NULL;
//    char             *k;
    struct db_spec  *spec = NULL;
    cg_var           *v = NULL;
    char             *bstr;
    int               uniquevars = 0;
    int               partial = 0;
    cg_var           *cv; 
    int               len;

    /*
     * Identify what is called a 'superleaf'. This is an XML node with element
     * children which in turn do not have sub-element.
     * Example: x is a superleaf: <x><a>text</a><b/><c attr="foo/></x>
     */
    superleaf = 0;
    xc = NULL;

    /*
     * return matching database specification and specification key.
     * or a partial match, eg if[].inet would partially match if[].inet.address[]
     */
    if (key2spec(xn->xn_name, basekey0, dbspec, &spec, 
		 &partial, &basekey) < 0)
	goto catch;
    /* actual key */
    if (key0){
	len = strlen(key0) + 1 + strlen(xn->xn_name);
	if ((key = malloc(len+1)) == NULL)
	    goto catch;
	snprintf(key, len+1, "%s.%s", key0, xn->xn_name);
    }
    else
	if ((key = strdup(xn->xn_name)) == NULL)
	    goto catch;

    if (spec == NULL){
	if (partial)
	    goto loop;
	retval = 0;
	goto catch;
    }
    /*
     * if this is a vector we can get its unique vars and make it
     * so we should transform it.
     * Otherwise we should transform if it has a proper spec
     * Actually maybe that is always when we should tranform it?
     */
    if (key_isvector(basekey)){
	v = NULL; 		
	while ((v = cvec_each(db_spec2cvec(spec), v)))
	    if (cv_flag(v, V_UNIQUE) &&
		!cvec_find(uv, cv_name_get(v))){
		/* push uniquevars */
		if ((bstr = xml_get_body2(xn, cv_name_get(v))) == NULL){
		    clicon_log(LOG_WARNING, "%s: xml should contain unique variable %s", 
			       __FUNCTION__, cv_name_get(v));
		    goto catch; /* bad xml */
		}
		if ((cv = cvec_add(uv, cv_type_get(v))) == NULL){
		    clicon_err(OE_UNIX, errno, "cvec_add");
		    goto catch;
		}
		if (cv_name_set(cv, cv_name_get(v)) == NULL)
		    goto catch;
		cv_flag_set(cv, cv_flag(v, 0xff));
		cv_parse(bstr, cv);
		uniquevars++;
	    }
	if (uniquevars == 0) /* bad spec */
	    clicon_log(LOG_WARNING, "%s: xml should contain unique variable %s", 
		    __FUNCTION__, xn->xn_name);
	if (uniquevars > 1) /* bad spec */
	    clicon_log(LOG_WARNING, "%s: xml should contain exactly one new unique variable %s", 
		    __FUNCTION__, xn->xn_name);
    }
    /* At least one sub is a leaf, then mark this node as superleaf
       and transform to DB */

    if (!leaf(xn))
	while ((xc = xml_child_each(xn, xc, XML_ELEMENT)) != NULL)
	    if (leaf(xc)){
		superleaf++;
		break;
	    }
    
    /* 
     */
    if (superleaf){
	if ((xml2db_transform_key(xn, dbspec, dbname, 
				  key_isvector(basekey), 
				  &key, spec, uv)) < 0)
	    goto catch;
    }
  loop:
    xc = NULL;
    while ((xc = xml_child_each(xn, xc, XML_ELEMENT)) != NULL)
	if (!leaf(xc)){
	    /* XXX: Se skillnad mellan basekey och faktisk key. */
	    if (xml2db_1(xc, dbspec, dbname, uv, basekey, key) < 0)
		goto catch;
	}
    retval = 0;
  catch: /* note : no unchunk here: recursion */
    /* pop uniquevars */
    while (uniquevars--){
	if (cvec_len(uv) > 0){
	    cv = cvec_i(uv, cvec_len(uv)-1);
	    cv_reset(cv);
	    cvec_del(uv, cv);

	}
    }
    if (key)
	free(key);
    if (basekey)
	free(basekey);
    return retval;
}


/*
 * xml2db
 * Map an xml parse-tree to a database
 */
int 
xml2db(struct xml_node *xt, struct db_spec *dbspec, char *dbname)
{
    struct xml_node *x = NULL;
    int retval = 0;
    cvec *uv;

    /* skip top level (which is 'clicon' or something */
    if ((uv = cvec_new(0)) == NULL) 
	goto catch;
    while ((x = xml_child_each(xt, x, XML_ELEMENT)) != NULL)
	if (xml2db_1(x, dbspec, dbname, uv, NULL, NULL) < 0)
	    goto catch;
    retval = 0;
  catch:
    if (uv)
	cvec_free(uv);
    return retval;
}

/*
 * save_db_to_xml
 * Transform a db into XML and save into a file
 */
int
save_db_to_xml(char *filename, struct db_spec *dbspec, char *dbname)
{
    FILE *f;
    struct xml_node *xn;

    if ((f = fopen(filename, "wb")) == NULL){
	clicon_err(OE_CFG, errno, "Creating file %s", filename);
	return -1;
    } 
    if ((xn = db2xml(dbname, dbspec, "clicon")) == NULL) {
	fclose(f);
	clicon_err(OE_CFG, errno, "Formatting config XML %s", filename);
	return -1;
    }

    xml_to_file(f, xn, 0, 1);
    fclose(f);
    xml_free(xn);

    return 0;

}

/*
 * load_xml_to_db
 * Load a saved XML file into a db
 */
int
load_xml_to_db(char *xmlfile, struct db_spec *dbspec, char *dbname)
{
    int fd = -1;
    int retval = -1;
    int eof;
    struct xml_node *xt;
    struct xml_node *xn = NULL; 
    
    if ((fd = open(xmlfile, O_RDONLY)) < 0){
	clicon_err(OE_UNIX, errno, "%s: open(%s)", __FUNCTION__, xmlfile);
	return -1;
    }
    /* XXX: if non-xml file, why no error code? */
    if (xml_parse_fd(fd, &xt, &eof, "</clicon>") < 0)
	goto catch;
    if (!xt->xn_nrchildren){
	clicon_err(OE_XML, errno, "%s: no children", __FUNCTION__);
	goto catch;
    }
    xn = xt->xn_children[0];

    xml_prune(xt, xn, 0); /* kludge to remove top-level tag (eg clicon) */
    xn->xn_parent = NULL;
    xml_free(xt);
    if (xml2db(xn, dbspec, dbname) < 0)
	goto catch;
    retval = 0;

  catch:
    if (fd != -1)
	close(fd);
    if (xn)
	xml_free(xn);
    return retval;
}


/* x is element and has eactly one child which in turn has none */
static int
tleaf(struct xml_node *x)
{
    struct xml_node *c;

    if (x->xn_type != XML_ELEMENT)
	return 0;
    if (x->xn_nrchildren != 1)
	return 0;
    c = x->xn_children[0];
    return (c->xn_nrchildren == 0);
}


/*
 * xml2txt. Translate XML -> TEXT
 * Displays 'junos-like' text for a configuration based on XML.
 * XXX: includes kludges for junos syntax
 */
#define KLUDGES_FOR_JUNOS 0
int 
xml2txt(FILE *f, struct xml_node *x, int level)
{
    struct xml_node *xe = NULL;
    int              children=0;
    char            *term;
    int              retval = -1;
    struct xml_node *xname;

    xe = NULL;     /* count children */
    while ((xe = xml_child_each(x, xe, -1)) != NULL)
	children++;
    if (!children){ 
	if (x->xn_type == XML_BODY){
	    /* Kludge for escaping encrypted passwords */
	    if (strcmp(x->xn_parent->xn_name, "encrypted-password")==0)
		term = chunk_sprintf(__FUNCTION__, "\"%s\"", x->xn_value);
	    else
		term = x->xn_value;
	}
	else{
	    fprintf(f, "%*s", 4*level, "");
	    term = x->xn_name;
	}
	fprintf(f, "%s;\n", term);
	retval = 0;
	goto done;
    }
    fprintf(f, "%*s", 4*level, "");
#if KLUDGES_FOR_JUNOS
    if (strcmp(x->xn_name, "interface")== 0 || 
	strcmp(x->xn_name, "prefix-list-item")== 0)
	;
    else
#endif
	{
	    if (strcmp(x->xn_name, "name") != 0)
		fprintf(f, "%s ", x->xn_name);
    }
    if ((xname = xml_find(x, "name")) != NULL){
	if (children > 1)
	    fprintf(f, "%s ", xml_get_body(xname));
	if (!tleaf(x))
	    fprintf(f, "{\n");
    }
    else
	{
	if (!tleaf(x))
	    fprintf(f, "{\n");
    }
    xe = NULL;
    while ((xe = xml_child_each(x, xe, -1)) != NULL){
	if (xe->xn_type == XML_ELEMENT &&  (strcmp(xe->xn_name, "name")==0) && 
	    (children > 1)) /* skip if this is a name element (unless 0 children) */
	    continue;
	if (xml2txt(f, xe, level+1) < 0)
	    break;
    }
    if (!tleaf(x))
	fprintf(f, "%*s}\n", 4*level, "");
    retval = 0;
  done:
    return retval;
}

/*
 * xml2cli. Translate XML -> CLI commands
 * Howto: join strings and pass them down. 
 * Identify unique/index keywords for correct set syntax.
 * Args:
 *  f:        where to print cli commands
 *  x:        xml parse-tree (to translate)
 *  prepend0: Print this text in front of all commands.
 *  label:    memory chunk allocation label
 */
int 
xml2cli(FILE              *f, 
	struct xml_node   *x, 
	char              *prepend0, 
	enum genmodel_type gt,
	const char        *label)
{
    struct xml_node *xe = NULL;
    char            *term;
    char            *prepend;
    int              retval = -1;
    int              bool;

    if (!x->xn_nrchildren){
	if (x->xn_type == XML_BODY)
	    term = x->xn_value;
	else
	    term = x->xn_name;
	if (prepend0)
	    fprintf(f, "%s ", prepend0);
	fprintf(f, "%s\n", term);
	retval = 0;
	goto done;
    }
    prepend = "";
    if (prepend0)
	if ((prepend = chunk_sprintf(label, "%s%s", prepend, prepend0)) == NULL)
	    goto done;
/* bool determines when to print a variable keyword:
   !leaf           T for all (ie parameter)
   index GT_NONE   F
   index GT_VARS   F
   index GT_ALL    T
   !index GT_NONE  F
   !index GT_VARS  T
   !index GT_ALL   T
 */
    bool = !leaf(x) || gt == GT_ALL || (gt == GT_VARS && !x->xn_index);
//    bool = (!x->xn_index || gt == GT_ALL);
    if (bool &&
	(prepend = chunk_sprintf(label, "%s%s%s", 
					prepend, 
					strlen(prepend)?" ":"",
					x->xn_name)) == NULL)
	goto done;
    xe = NULL;
    /* First child is unique, then add that, before looping. */
    while ((xe = xml_child_each(x, xe, -1)) != NULL){
	if (xml2cli(f, xe, prepend, gt, label) < 0)
	    goto done;
	if (xe->xn_index){ /* assume index is first, otherwise need one more while */
	    if (gt ==GT_ALL && (prepend = chunk_sprintf(label, "%s %s", 
							prepend, 
							xe->xn_name)) == NULL)

		goto done;
	    if ((prepend = chunk_sprintf(label, "%s %s", 
					 prepend, 
					 xe->xn_children[0]->xn_value)) == NULL)
		goto done;
	}
    }
    retval = 0;
  done:
    return retval;

}
