/*
 *  CVS Version: $Id: clicon_log.c,v 1.6 2013/08/01 09:15:46 olof Exp $
 *
  Copyright (C) 2009-2013 Olof Hagsand and Benny Holmgren

  This file is part of CLICON.

  CLICON is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 3 of the License, or
  (at your option) any later version.

  CLICON is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with CLICON; see the file COPYING.  If not, see
  <http://www.gnu.org/licenses/>.

 *
 * Regular logging and debugging. Syslog using levels.
 */

#ifdef HAVE_CONFIG_H
#include "clicon_config.h" /* generated by config & autoconf */
#endif

#include <stdio.h>
#include <stdarg.h>
#include <fcntl.h>
#include <unistd.h>
#include <syslog.h>
#include <string.h>
#include <time.h>
#include <errno.h>
#include <sys/time.h>
#include <sys/types.h>

/* clicon */
#include "clicon_log.h"

/* The global debug level */
int debug = 0;
static int _debug_syslog = 0;

/*
 * clicon_log_init
 * Initialize system logger.
 * NOTE: applies to errors too.
 * ident is the prefix that appears on syslog (eg 'cli')
 * options: see syslog(3). Example: LOG_PERROR logs to stderr.
 * upto: log priority
 */
int
clicon_log_init(char *ident, int upto, int err)
{
    if (setlogmask(LOG_UPTO(upto)) < 0)
	/* Cant syslog here */
	fprintf(stderr, "%s: setlogmask: %s\n", __FUNCTION__, strerror(errno)); 
    openlog(ident, LOG_PID | (err?LOG_PERROR:0), LOG_USER);
    return 0;
}

/*
 * clicon_log
 * In arguments are:
 * default log-level is LOG_NOTICE.
 */
int
clicon_log(int level, char *format, ...)
{
    va_list args;

    va_start(args, format);
    vsyslog(LOG_MAKEPRI(LOG_USER, level), format, args);
    va_end(args);
    return 0;
}

/*
 * clicon_debug_init
 * log dbg messages upto 'level'
 * log on stderr, else to syslog
 */
int
clicon_debug_init(int level, int syslog)
{
    int mask;

    debug = level;
    mask = setlogmask(0);
    _debug_syslog = syslog;
    if (debug)
	setlogmask(LOG_MASK(LOG_DEBUG) | mask);
    else
	setlogmask(~LOG_MASK(LOG_DEBUG) & mask);

    return 0;
}

/*
 * clicon_debug
 * print a debug message to syslog(LOG_DEBUG) if the debug level passed in the 
 * function is equal to or lower than the one set by clicon_debug_init.
 * That is, only print debug messages <= than what you want.
 * You can therefore have clicon_debug(0,...) which should always be called
 * (But then you may not see them in the syslog due to the level).
 */
int
clicon_debug(int dbglevel, char *format, ...)
{
    va_list args;

    if (dbglevel > debug)
	return 0;
    if (_debug_syslog) {
	va_start(args, format);
	vsyslog(LOG_MAKEPRI(LOG_USER, LOG_DEBUG), format, args);
	va_end(args);
    }
    va_start(args, format);
    vfprintf(stderr, format, args);
    va_end(args);
    fprintf(stderr, "\n");
    return 0;
}

char *
mon2name(int md)
{
    switch(md){
    case 0: return "Jan";
    case 1: return "Feb";
    case 2: return "Mar";
    case 3: return "Apr";
    case 4: return "May";
    case 5: return "Jun";
    case 6: return "Jul";
    case 7: return "Aug";
    case 8: return "Sep";
    case 9: return "Oct";
    case 10: return "Nov";
    case 11: return "Dec";
    default:
	break;
    }
    return NULL;
}

