/*
 *  CVS Version: $Id: config_handle.c,v 1.10 2013/08/31 06:32:46 benny Exp $
 *
  Copyright (C) 2009-2013 Olof Hagsand and Benny Holmgren

  This file is part of CLICON.

  CLICON is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 3 of the License, or
  (at your option) any later version.

  CLICON is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with CLICON; see the file COPYING.  If not, see
  <http://www.gnu.org/licenses/>.

 */

#ifdef HAVE_CONFIG_H
#include "clicon_config.h" /* generated by config & autoconf */
#endif

#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <stdlib.h>
#include <inttypes.h>
#include <dirent.h>
#include <errno.h>
#include <assert.h>
#include <sys/types.h>
#include <regex.h>
#include <netinet/in.h>

/* cligen */
#include <cligen/cligen.h>

/* clicon */
#include <clicon/clicon.h>

#include "clicon_backend_api.h"
#include "config_dbdiff.h"
#include "config_dbdep.h"

/* header part is copied from struct clicon_handle in lib/src/clicon_handle.c */

#define CLICON_MAGIC 0x99aafabe

#define handle(h) (assert(clicon_handle_check(h)==0),(struct backend_handle *)(h))

/*
 * config_handle
 * first part of this is header, same for clicon_handle and cli_handle.
 * This file should only contain access functions for the _specific_
 * entries in the struct below.
 */
struct backend_handle {
    int                      cb_magic;    /* magic (HDR)*/
    clicon_hash_t           *cb_copt;     /* clicon option list (HDR) */
    clicon_hash_t           *cb_data;     /* internal clicon data (HDR) */
    dbdep_t                 *cb_dbdep;    /* Database dependencies: commit checks */
};

/*
 * backend_handle_init
 * returns a clicon config handle for other CLICON API calls
 */
clicon_handle
backend_handle_init(void)
{
    return clicon_handle_init0(sizeof(struct backend_handle));
}

/*
 * clicon_backend_handle_exit
 * returns a clicon handle for other CLICON API calls
 */
int
backend_handle_exit(clicon_handle h)
{
    dbdeps_free(h); 
    clicon_handle_exit(h); /* frees h and options */
    return 0;
}

dbdep_t *
backend_dbdep(clicon_handle h)
{
    struct backend_handle *cb = handle(h);
    
    return cb->cb_dbdep;
}

int
backend_dbdep_set(clicon_handle h, dbdep_t *dbdep)
{
    struct backend_handle *cb = handle(h);

    cb->cb_dbdep = dbdep;
    return 0;
}
