/*
 * Copyright (C) 2009-2015 Olof Hagsand and Benny Holmgren
 *
 * This file is part of CLICON.
 * 
 * CLICON is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 *  CLICON is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CLICON; see the file COPYING.  If not, see
 * <http://www.gnu.org/licenses/>.
 */
#ifdef HAVE_CONFIG_H
#include "clicon_config.h" /* generated by config & autoconf */
#endif

#include <Python.h>

/* clicon */
#include <cligen/cligen.h>
#include <clicon/clicon.h>

/* pyclicon */
#include "libpyclicon.h"
#include "pyclicon.h"


typedef struct _clicon {
    PyObject_HEAD
} clicon;

/*
 * Keep an internal reference to the CLIgen module
 */
PyObject *
__cligen_module()
{
    static PyObject *cligen = NULL;

    if (cligen == NULL)
	cligen = PyImport_ImportModule("cligen");

    return cligen;
}


static PyMethodDef Clicon_module_methods[] = {
    {"_clicon_options", (PyCFunction)Clicon_options, METH_VARARGS,
     "Get CLICON options dictionary"
    },
    {"_clicon_option", (PyCFunction)Clicon_option, METH_VARARGS,
     "Get CLICON option"
    },
    {"_clicon_option_set", (PyCFunction)Clicon_option_set, METH_VARARGS,
     "Set CLICON option"
    },
    {"_clicon_option_del", (PyCFunction)Clicon_option_del, METH_VARARGS,
     "Delete CLICON option"
    },
    {"_clicon_option_exists", (PyCFunction)Clicon_option_exists, METH_VARARGS,
     "Check if a CLICON option is set"
    },
    
    {"_clicon_log", (PyCFunction)Clicon_log, METH_VARARGS,
     "Create CLICON log message"
    },
    
    {"_clicon_debug", (PyCFunction)Clicon_debug, METH_VARARGS,
     "Create CLICON log message"
    },
    
    {"_clicon_err", (PyCFunction)Clicon_err, METH_VARARGS,
     "Create CLICON error message"
    },
    
    
    {"_clicon_strerror", (PyCFunction)Clicon_strerror, METH_VARARGS,
     "Get CLICON error string"
    },
    
    {"_clicon_err_reset", (PyCFunction)Clicon_err_reset, METH_NOARGS,
     "Reset CLICON error state"
    },

    {NULL, NULL, 0, NULL}
};

MOD_INIT(_clicon)
{
    PyObject* m;
    int CliconDB_init_object(PyObject *m);

    MOD_DEF(m, "_clicon", "Python bindings for CLICON", Clicon_module_methods);
    if (m == NULL)
        return MOD_ERROR_VAL;
    
    PyModule_AddStringConstant(m, (char *) "CLICON_BUILDSTR", CLICON_BUILDSTR);
    PyModule_AddStringConstant(m, (char *) "CLICON_VERSION", CLICON_VERSION);
    
    /* Make sure we find the CLIgen module */
    if (__cligen_module() == NULL)
        return MOD_ERROR_VAL;

    if (CliconDB_init_object(m) < 0)
        return MOD_ERROR_VAL;
    if (Clicon_log_init(m) < 0)
        return MOD_ERROR_VAL;
    if (Clicon_err_init(m) < 0)
        return MOD_ERROR_VAL;

    return MOD_SUCCESS_VAL(m);
}

